name: DeploymentPipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
    #   Utilise le code base du repository
        uses: actions/checkout@v4
      - name: setup Nodejs environment
    #   Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - name: Install package
        run: npm ci
      - name: build
        run: npm run build && rm -rf docs && mv dist docs
        # On commit les modification effectuées pour les persister dans le repository
        # commit tout changement à retourner dans le repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: push build


